import polars as pl
import pandas as pd
import logging
from typing import Dict, Any
from app.tools.base import BaseNode

logger = logging.getLogger(__name__)

class SoccerReaderNode(BaseNode):
    MANIFEST = {
        "id": "soccer_reader",
        "name": "Soccer Predictor Reader",
        "category": "ai",
        "icon": "MessageSquare",
        "description": "Transforms Engine predictions and odds into a rich, human-readable Scout Report narrative.",
        "ui_schema": [
            {
                "field": "help",
                "type": "help_text",
                "label": "",
                "content": "<strong>📖 Engine Pundit:</strong> This tool reads the predictions generated by the Soccer Predictor and creates a rich, verbose Scout Report for every match."
            },
            {
                "field": "homeTeamCol",
                "type": "column_select",
                "label": "Home Team Column",
                "default": "HomeTeam"
            },
            {
                "field": "awayTeamCol",
                "type": "column_select",
                "label": "Away Team Column",
                "default": "AwayTeam"
            },
            {
                "field": "ftHomePredCol",
                "type": "column_select",
                "label": "Predicted FT Home Score (Optional)",
                "default": "Predicted_FT_HomeScore"
            },
            {
                "field": "ftAwayPredCol",
                "type": "column_select",
                "label": "Predicted FT Away Score (Optional)",
                "default": "Predicted_FT_AwayScore"
            },
            {
                "field": "htHomePredCol",
                "type": "column_select",
                "label": "Predicted HT Home Score (Optional)",
                "default": "Predicted_HT_HomeScore"
            },
            {
                "field": "htAwayPredCol",
                "type": "column_select",
                "label": "Predicted HT Away Score (Optional)",
                "default": "Predicted_HT_AwayScore"
            },
            {
                "field": "shHomePredCol",
                "type": "column_select",
                "label": "Predicted SH Home Score (Optional)",
                "default": "Predicted_SH_HomeScore"
            },
            {
                "field": "shAwayPredCol",
                "type": "column_select",
                "label": "Predicted SH Away Score (Optional)",
                "default": "Predicted_SH_AwayScore"
            },
            {
                "field": "homeOddsCol",
                "type": "column_select",
                "label": "Home Win Odds (Optional)",
                "default": "B365H"
            },
            {
                "field": "awayOddsCol",
                "type": "column_select",
                "label": "Away Win Odds (Optional)",
                "default": "B365A"
            }
        ],
        "defaultParams": {
            "homeTeamCol": "HomeTeam",
            "awayTeamCol": "AwayTeam",
            "ftHomePredCol": "Predicted_FT_HomeScore",
            "ftAwayPredCol": "Predicted_FT_AwayScore",
            "htHomePredCol": "Predicted_HT_HomeScore",
            "htAwayPredCol": "Predicted_HT_AwayScore",
            "shHomePredCol": "Predicted_SH_HomeScore",
            "shAwayPredCol": "Predicted_SH_AwayScore",
            "homeOddsCol": "B365H",
            "awayOddsCol": "B365A"
        }
    }

    def execute(self, inputs: Dict[str, pl.DataFrame]) -> pl.DataFrame:
        df = inputs.get("input")
        if df is None:
            raise ValueError("Soccer Predictor Reader requires an incoming data stream.")

        home_team_col = self.parameters.get("homeTeamCol")
        away_team_col = self.parameters.get("awayTeamCol")
        ft_h_col = self.parameters.get("ftHomePredCol")
        ft_a_col = self.parameters.get("ftAwayPredCol")
        ht_h_col = self.parameters.get("htHomePredCol")
        ht_a_col = self.parameters.get("htAwayPredCol")
        sh_h_col = self.parameters.get("shHomePredCol")
        sh_a_col = self.parameters.get("shAwayPredCol")
        h_odds_col = self.parameters.get("homeOddsCol")
        a_odds_col = self.parameters.get("awayOddsCol")

        columns = df.columns
        if home_team_col not in columns or away_team_col not in columns:
            logger.warning(f"Soccer Reader: Missing Team columns {home_team_col} or {away_team_col}")
            return df

        pd_df = df.to_pandas()
        narratives = []

        for _, row in pd_df.iterrows():
            home = row[home_team_col]
            away = row[away_team_col]
            
            ft_h = row[ft_h_col] if ft_h_col in columns else None
            ft_a = row[ft_a_col] if ft_a_col in columns else None
            ht_h = row[ht_h_col] if ht_h_col in columns else None
            ht_a = row[ht_a_col] if ht_a_col in columns else None
            sh_h = row[sh_h_col] if sh_h_col in columns else None
            sh_a = row[sh_a_col] if sh_a_col in columns else None
            h_odds = row[h_odds_col] if h_odds_col in columns else None
            a_odds = row[a_odds_col] if a_odds_col in columns else None
            
            # Form / Momentum Columns (from Football Engine)
            h_form = row['HomeTeam_Form_Last5_Pts'] if 'HomeTeam_Form_Last5_Pts' in columns else None
            a_form = row['AwayTeam_Form_Last5_Pts'] if 'AwayTeam_Form_Last5_Pts' in columns else None
            h_pts = float(h_form) if h_form is not None else 0
            a_pts = float(a_form) if a_form is not None else 0
            h_mom = row['HomeTeam_Scoring_Momentum_L3'] if 'HomeTeam_Scoring_Momentum_L3' in columns else None
            a_mom = row['AwayTeam_Scoring_Momentum_L3'] if 'AwayTeam_Scoring_Momentum_L3' in columns else None

            parts = []
            
            # FT Prediction Logic
            if pd.notna(ft_h) and pd.notna(ft_a):
                try:
                    fh = int(round(float(ft_h)))
                    fa = int(round(float(ft_a)))
                    
                    if fh > fa:
                        if h_pts > a_pts:
                            parts.append(f"In what promises to be a thrilling, high-scoring clash, {home} is tipped by the Engine to secure a {fh}-{fa} victory over {away}.")
                        elif h_pts == a_pts:
                            parts.append(f"The Engine expects a tight, tactical affair with {home} edging out {away} for a narrow {fh}-{fa} win.")
                    elif fa > fh:
                        if a_pts > h_pts:
                            parts.append(f"Expect fireworks from the visitors as {away} is predicted to outgun {home} in an entertaining {fa}-{fh} away win.")
                        else:
                            parts.append(f"A gritty away performance is on the cards. The Engine predicts {away} to grind out a {fa}-{fh} victory against {home}.")
                    else:
                        if h_pts + a_pts == 0:
                            parts.append(f"This match has all the makings of a defensive stalemate, with the Engine predicting a 0-0 draw between {home} and {away}.")
                        else:
                            parts.append(f"A closely fought battle is expected, with the Engine pointing towards a highly competitive {fh}-{fa} draw between {home} and {away}.")
                except:
                    parts.append(f"The Engine is analyzing the clash between {home} and {away}.")
            else:
                parts.append(f"The Engine is analyzing the clash between {home} and {away}.")

            # HT vs FT / SH Logic (Momentum shifts)
            if pd.notna(ht_h) and pd.notna(ht_a) and pd.notna(ft_h) and pd.notna(ft_a):
                try:
                    hh = float(ht_h)
                    ha = float(ht_a)
                    fh = float(ft_h)
                    fa = float(ft_a)
                    
                    # If we have SH directly from Predictor, use it. Otherwise derive from FT - HT.
                    h_2nd_half = float(sh_h) if pd.notna(sh_h) else (fh - hh)
                    a_2nd_half = float(sh_a) if pd.notna(sh_a) else (fa - ha)
                    
                    if h_2nd_half > a_2nd_half and h_2nd_half >= 1.0:
                        parts.append(f"Watch for a massive 2nd half surge from {home}, who are notoriously strong finishers in this scenario.")
                    elif a_2nd_half > h_2nd_half and a_2nd_half >= 1.0:
                        parts.append(f"The 2nd half is where {away} really turns up the heat, expecting to outscore their opponents after the break.")
                    elif hh > ha and fh > fa:
                        parts.append(f"{home} is predicted to come out of the gates blazing in the 1st half and sustain their lead.")
                    elif ha > hh and fa > fh:
                        parts.append(f"{away} looks incredibly dangerous in the 1st half and will aim to kill the game early.")
                except:
                    pass

            # Odds Value Logic
            if pd.notna(h_odds) and pd.notna(a_odds) and pd.notna(ft_h) and pd.notna(ft_a):
                try:
                    fh = float(ft_h)
                    fa = float(ft_a)
                    ho = float(h_odds)
                    ao = float(a_odds)
                    
                    if fh > fa and ho >= 2.0:
                        parts.append(f"With bookmakers pricing a home win at {ho:.2f}, there is tremendous betting value backing {home} here.")
                    if fh < fa and ao > 2.5:
                        parts.append(f"The Engine spots a huge underdog opportunity! At odds of {ao:.2f}, {away} is a highly lucrative pick.")
                    elif fh > fa and ho < 1.5:
                        parts.append(f"{home} is a massive favorite at {ho:.2f}, but the Engine confidently backs them to get the job done.")
                except:
                    pass
                    
            # Momentum / Form Logic
            if pd.notna(h_form) and pd.notna(a_form):
                try:
                    h_pts = float(h_form)
                    a_pts = float(a_form)
                    
                    if h_pts >= 12 and a_pts < 5:
                        parts.append(f"Momentum is completely on the home side; {home} has been on an absolute tear recently, while {away} is struggling immensely.")
                    elif a_pts >= 12 and h_pts < 5:
                        parts.append(f"The form book strongly favors the visitors. {away} is riding a massive wave of momentum, whereas {home} has been in dismal form.")
                    elif h_pts >= 10 and a_pts >= 10:
                        parts.append(f"Both teams come into this clash with fantastic recent momentum, making this an unstoppable force meeting an immovable object.")
                    elif h_pts <= 3 and a_pts <= 3:
                        parts.append(f"Neither side has any momentum coming into this match, with both {home} and {away} desperately searching for a much-needed win.")
                except:
                    pass
            
            if not parts:
                narratives.append(f"Match preview for {home} vs {away}.")
            else:
                narratives.append(" ".join(parts))

        pd_df["Engine_Match_Narrative"] = narratives
        logger.info(f"Soccer Predictor Reader generated {len(pd_df)} intelligent scout reports.")
        
        return pl.from_pandas(pd_df)
